"""initialize_schema

Revision ID: 428fa15c271a
Revises: 
Create Date: 2025-08-16 14:34:47.633108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '428fa15c271a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scam_reports',
    sa.Column('report_id', sa.String(), nullable=False),
    sa.Column('scam_incident_date', sa.Date(), nullable=False),
    sa.Column('scam_report_date', sa.Date(), nullable=False),
    sa.Column('scam_type', sa.String(), nullable=True),
    sa.Column('scam_approach_platform', sa.String(), nullable=True),
    sa.Column('scam_communication_platform', sa.String(), nullable=True),
    sa.Column('scam_transaction_type', sa.String(), nullable=True),
    sa.Column('scam_beneficiary_platform', sa.String(), nullable=True),
    sa.Column('scam_beneficiary_identifier', sa.String(), nullable=True),
    sa.Column('scam_contact_no', sa.String(), nullable=True),
    sa.Column('scam_email', sa.String(), nullable=True),
    sa.Column('scam_moniker', sa.String(), nullable=True),
    sa.Column('scam_url_link', sa.String(), nullable=True),
    sa.Column('scam_amount_lost', sa.Float(), nullable=True),
    sa.Column('scam_incident_description', sa.String(), nullable=True),
    sa.Column('embedding', Vector(dim=384), nullable=True),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_table('strategy',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('strategy_type', sa.String(), nullable=False),
    sa.Column('response', sa.Text(), nullable=False),
    sa.Column('success_score', sa.Float(), nullable=False),
    sa.Column('user_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('retrieval_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('strategy')
    op.drop_table('scam_reports')
    # ### end Alembic commands ###
