# demographic_configs:
#   ecommerce:
#     age_ranges:
#       - min_age: 18
#         max_age: 40
#         probability: 0.6
#       - min_age: 41
#         max_age: 60
#         probability: 0.3
#       - min_age: 61
#         max_age: 80
#         probability: 0.1
#     occupations:
#       - occupation: Software Engineer
#         probability: 0.1
#       - occupation: Student
#         probability: 0.1
#       - occupation: Marketing Executive
#         probability: 0.08
#       - occupation: Sales Manager
#         probability: 0.07
#       - occupation: Teacher
#         probability: 0.07
#       - occupation: Unemployed
#         probability: 0.07
#       - occupation: Retail Assistant
#         probability: 0.06
#       - occupation: Graphic Designer
#         probability: 0.06
#       - occupation: Customer Service Officer
#         probability: 0.06
#       - occupation: Freelancer
#         probability: 0.06
#       - occupation: Data Analyst
#         probability: 0.05
#       - occupation: Delivery Driver
#         probability: 0.05
#       - occupation: Social Media Manager
#         probability: 0.05
#       - occupation: Bank Teller
#         probability: 0.05
#       - occupation: Business Owner
#         probability: 0.04
#     nationality_weights:
#       Singaporean: 0.80
#       Malaysian: 0.15
#       Indian: 0.02
#       Filipino: 0.01
#       Bangladeshi: 0.01
#       American: 0.005
#       British: 0.005
#     race_weights:
#       Singaporean:
#         - race: Chinese
#           probability: 0.5
#         - race: Malay
#           probability: 0.2
#         - race: Indian
#           probability: 0.2
#         - race: Eurasian
#           probability: 0.1
#       Malaysian:
#         - race: Malay
#           probability: 0.4
#         - race: Chinese
#           probability: 0.3
#         - race: Indian
#           probability: 0.2
#         - race: Other
#           probability: 0.1
#       Indian:
#         - race: Indian
#           probability: 0.9
#         - race: Other
#           probability: 0.1
#       Filipino:
#         - race: Filipino
#           probability: 0.9
#         - race: Other
#           probability: 0.1
#       Bangladeshi:
#         - race: Bangladeshi
#           probability: 0.9
#         - race: Other
#           probability: 0.1
#       American:
#         - race: Caucasian
#           probability: 0.7
#         - race: Other
#           probability: 0.3
#       British:
#         - race: Caucasian
#           probability: 0.7
#         - race: Other
#           probability: 0.3
#     sex_weights:
#       Male: 0.5
#       Female: 0.5
#   phishing:
#     age_ranges:
#       - min_age: 18
#         max_age: 40
#         probability: 0.4
#       - min_age: 41
#         max_age: 60
#         probability: 0.4
#       - min_age: 61
#         max_age: 80
#         probability: 0.2
#     occupations:
#       - occupation: Office Clerk
#         probability: 0.08
#       - occupation: Student
#         probability: 0.08
#       - occupation: IT Support
#         probability: 0.07
#       - occupation: Nurse
#         probability: 0.07
#       - occupation: Retail Manager
#         probability: 0.07
#       - occupation: Administrative Assistant
#         probability: 0.06
#       - occupation: Call Center Agent
#         probability: 0.06
#       - occupation: Teacher
#         probability: 0.06
#       - occupation: Software Developer
#         probability: 0.06
#       - occupation: Accountant
#         probability: 0.06
#       - occupation: Security Guard
#         probability: 0.05
#       - occupation: Marketing Coordinator
#         probability: 0.05
#       - occupation: Logistics Coordinator
#         probability: 0.05
#       - occupation: Freelance Writer
#         probability: 0.05
#       - occupation: Customer Support Specialist
#         probability: 0.04
#     nationality_weights:
#       Singaporean: 0.70
#       Malaysian: 0.12
#       Indian: 0.08
#       Filipino: 0.05
#       Bangladeshi: 0.03
#       American: 0.01
#       British: 0.01
#     race_weights:
#       Singaporean:
#         - race: Chinese
#           probability: 0.5
#         - race: Malay
#           probability: 0.2
#         - race: Indian
#           probability: 0.2
#         - race: Eurasian
#           probability: 0.1
#       Malaysian:
#         - race: Malay
#           probability: 0.35
#         - race: Chinese
#           probability: 0.35
#         - race: Indian
#           probability: 0.2
#         - race: Other
#           probability: 0.1
#       Indian:
#         - race: Indian
#           probability: 0.9
#         - race: Other
#           probability: 0.1
#       Filipino:
#         - race: Filipino
#           probability: 0.9
#         - race: Other
#           probability: 0.1
#       Bangladeshi:
#         - race: Bangladeshi
#           probability: 0.9
#         - race: Other
#           probability: 0.1
#       American:
#         - race: Caucasian
#           probability: 0.7
#         - race: Other
#           probability: 0.3
#       British:
#         - race: Caucasian
#           probability: 0.7
#         - race: Other
#           probability: 0.3
#     sex_weights:
#       Male: 0.5
#       Female: 0.5
#   government officials impersonation:
#     age_ranges:
#       - min_age: 18
#         max_age: 40
#         probability: 0.1
#       - min_age: 41
#         max_age: 60
#         probability: 0.3
#       - min_age: 61
#         max_age: 80
#         probability: 0.6
#     occupations:
#       - occupation: Retired
#         probability: 0.1
#       - occupation: Construction Worker
#         probability: 0.08
#       - occupation: Factory Worker
#         probability: 0.08
#       - occupation: Cleaner
#         probability: 0.07
#       - occupation: Security Guard
#         probability: 0.07
#       - occupation: Accountant
#         probability: 0.06
#       - occupation: Lawyer
#         probability: 0.06
#       - occupation: Doctor
#         probability: 0.06
#       - occupation: Teacher
#         probability: 0.06
#       - occupation: Driver
#         probability: 0.06
#       - occupation: Maintenance Technician
#         probability: 0.05
#       - occupation: Shop Assistant
#         probability: 0.05
#       - occupation: Administrative Officer
#         probability: 0.05
#       - occupation: Warehouse Worker
#         probability: 0.05
#       - occupation: Electrician
#         probability: 0.05
#     nationality_weights:
#       Singaporean: 0.60
#       Malaysian: 0.15
#       Indian: 0.10
#       Filipino: 0.08
#       Bangladeshi: 0.05
#       American: 0.01
#       British: 0.01
#     race_weights:
#       Singaporean:
#         - race: Chinese
#           probability: 0.4
#         - race: Malay
#           probability: 0.3
#         - race: Indian
#           probability: 0.2
#         - race: Eurasian
#           probability: 0.1
#       Malaysian:
#         - race: Malay
#           probability: 0.3
#         - race: Chinese
#           probability: 0.4
#         - race: Indian
#           probability: 0.2
#         - race: Other
#           probability: 0.1
#       Indian:
#         - race: Indian
#           probability: 0.9
#         - race: Other
#           probability: 0.1
#       Filipino:
#         - race: Filipino
#           probability: 0.9
#         - race: Other
#           probability: 0.1
#       Bangladeshi:
#         - race: Bangladeshi
#           probability: 0.9
#         - race: Other
#           probability: 0.1
#       American:
#         - race: Caucasian
#           probability: 0.7
#         - race: Other
#           probability: 0.3
#       British:
#         - race: Caucasian
#           probability: 0.7
#         - race: Other
#           probability: 0.3
#     sex_weights:
#       Male: 0.6
#       Female: 0.4

# race_name_lists:
#   Chinese:
#     male_first_names: ["Wei", "Hao", "Min", "Xin", "Li"]
#     female_first_names: ["Jia", "Ting", "Yan"]
#     last_names: ["Tan", "Lim", "Ng", "Lee", "Wong", "Goh", "Chua", "Chan"]
#   Malay:
#     male_first_names: ["Ahmad", "Mohammad", "Hassan"]
#     female_first_names: ["Nur", "Siti", "Aisyah", "Fatimah"]
#     last_names: ["Bin Abdullah", "Binte Rahman", "Bin Ismail", "Binte Zainal"]
#   Indian:
#     male_first_names: ["Arjun", "Vikram", "Rahul", "Sanjay"]
#     female_first_names: ["Priya", "Anita", "Meena"]
#     last_names: ["Singh", "Kumar", "Nair", "Pillai", "Menon", "Rao"]
#   Eurasian:
#     male_first_names: ["James", "Michael"]
#     female_first_names: ["Emma", "Sophia"]
#     last_names: ["Pereira", "De Souza", "Fernandez", "Gomes"]
#   Filipino:
#     male_first_names: ["Jose", "Juan"]
#     female_first_names: ["Maria", "Anna", "Clara"]
#     last_names: ["Santos", "Reyes", "Cruz", "Garcia"]
#   Bangladeshi:
#     male_first_names: ["Mohammad", "Abdul", "Rahim"]
#     female_first_names: ["Fatima", "Ayesha"]
#     last_names: ["Hossain", "Ahmed", "Khan", "Rahman"]
#   Caucasian:
#     male_first_names: ["James", "Michael", "William", "Harry"]
#     female_first_names: ["Emma", "Sophia", "Olivia", "Charlotte"]
#     last_names: ["Smith", "Johnson", "Brown", "Taylor", "Wilson"]
#   Other:
#     male_first_names: ["James", "Michael"]
#     female_first_names: ["Emma", "Sophia"]
#     last_names: ["Smith", "Brown", "Wilson", "Davis"]

# address_components:
#   streets:
#     [
#       "Ang Mo Kio Ave",
#       "Bedok North Rd",
#       "Bukit Batok St",
#       "Choa Chu Kang Loop",
#       "Clementi Ave",
#       "Hougang Ave",
#       "Jurong West St",
#       "Pasir Ris Dr",
#       "Sengkang East Way",
#       "Tampines St",
#       "Yishun Ring Rd",
#       "Orchard Rd",
#       "Geylang Rd",
#       "Serangoon Rd",
#       "Toa Payoh Lor",
#       "Woodlands Dr",
#       "Punggol Way",
#       "Bishan St",
#       "Marine Parade Rd",
#       "Eunos Crescent",
#       "Queenstown Rd",
#       "Balestier Rd",
#       "Jalan Besar",
#       "Commonwealth Ave",
#       "Upper Bukit Timah Rd",
#       "Chinatown Point",
#       "Tiong Bahru Rd",
#       "Kallang Bahru",
#       "Boon Lay Way",
#       "Admiralty Dr",
#     ]

# contact_no_prefix: "+65"

# email_domains: ["gmail.com", "yahoo.com.sg", "hotmail.com", "outlook.com"]

demographic_config:
  age_ranges:
    - min_age: 18
      max_age: 40
      probability: 0.37 # Averaged from originals: (0.6 + 0.4 + 0.1)/3
    - min_age: 41
      max_age: 60
      probability: 0.33 # Averaged: (0.3 + 0.4 + 0.3)/3
    - min_age: 61
      max_age: 80
      probability: 0.30 # Averaged: (0.1 + 0.2 + 0.6)/3
  occupations:
    # Combined and normalized from all scam types; removed duplicates and averaged probabilities
    - occupation: Software Engineer
      probability: 0.05 # Appears in some; adjusted
    - occupation: Student
      probability: 0.06
    - occupation: Marketing Executive
      probability: 0.04
    - occupation: Sales Manager
      probability: 0.04
    - occupation: Teacher
      probability: 0.06
    - occupation: Unemployed
      probability: 0.04
    - occupation: Retail Assistant
      probability: 0.04
    - occupation: Graphic Designer
      probability: 0.03
    - occupation: Customer Service Officer
      probability: 0.04
    - occupation: Freelancer
      probability: 0.04
    - occupation: Data Analyst
      probability: 0.03
    - occupation: Delivery Driver
      probability: 0.03
    - occupation: Social Media Manager
      probability: 0.03
    - occupation: Bank Teller
      probability: 0.03
    - occupation: Business Owner
      probability: 0.02
    - occupation: Office Clerk
      probability: 0.04
    - occupation: IT Support
      probability: 0.04
    - occupation: Nurse
      probability: 0.04
    - occupation: Retail Manager
      probability: 0.04
    - occupation: Administrative Assistant
      probability: 0.03
    - occupation: Call Center Agent
      probability: 0.03
    - occupation: Software Developer
      probability: 0.03
    - occupation: Accountant
      probability: 0.04
    - occupation: Security Guard
      probability: 0.04
    - occupation: Marketing Coordinator
      probability: 0.03
    - occupation: Logistics Coordinator
      probability: 0.03
    - occupation: Freelance Writer
      probability: 0.03
    - occupation: Customer Support Specialist
      probability: 0.02
    - occupation: Retired
      probability: 0.05
    - occupation: Construction Worker
      probability: 0.04
    - occupation: Factory Worker
      probability: 0.04
    - occupation: Cleaner
      probability: 0.04
    - occupation: Lawyer
      probability: 0.03
    - occupation: Doctor
      probability: 0.03
    - occupation: Driver
      probability: 0.03
    - occupation: Maintenance Technician
      probability: 0.03
    - occupation: Shop Assistant
      probability: 0.03
    - occupation: Administrative Officer
      probability: 0.03
    - occupation: Warehouse Worker
      probability: 0.03
    - occupation: Electrician
      probability: 0.03
  nationality_weights:
    Singaporean: 0.70 # Averaged: (0.80 + 0.70 + 0.60)/3
    Malaysian: 0.14 # Averaged: (0.15 + 0.12 + 0.15)/3
    Indian: 0.067 # Averaged
    Filipino: 0.047
    Bangladeshi: 0.03
    American: 0.008
    British: 0.008
  race_weights:
    Singaporean:
      - race: Chinese
        probability: 0.47 # Averaged across originals
      - race: Malay
        probability: 0.23
      - race: Indian
        probability: 0.20
      - race: Eurasian
        probability: 0.10
    Malaysian:
      - race: Malay
        probability: 0.35
      - race: Chinese
        probability: 0.35
      - race: Indian
        probability: 0.20
      - race: Other
        probability: 0.10
    Indian:
      - race: Indian
        probability: 0.90
      - race: Other
        probability: 0.10
    Filipino:
      - race: Filipino
        probability: 0.90
      - race: Other
        probability: 0.10
    Bangladeshi:
      - race: Bangladeshi
        probability: 0.90
      - race: Other
        probability: 0.10
    American:
      - race: Caucasian
        probability: 0.70
      - race: Other
        probability: 0.30
    British:
      - race: Caucasian
        probability: 0.70
      - race: Other
        probability: 0.30
  sex_weights:
    Male: 0.53 # Averaged: (0.5 + 0.5 + 0.6)/3
    Female: 0.47 # Averaged: (0.5 + 0.5 + 0.4)/3

race_name_lists:
  Chinese:
    male_first_names: ["Wei", "Hao", "Min", "Xin", "Li"]
    female_first_names: ["Jia", "Ting", "Yan"]
    last_names: ["Tan", "Lim", "Ng", "Lee", "Wong", "Goh", "Chua", "Chan"]
  Malay:
    male_first_names: ["Ahmad", "Mohammad", "Hassan"]
    female_first_names: ["Nur", "Siti", "Aisyah", "Fatimah"]
    last_names: ["Bin Abdullah", "Binte Rahman", "Bin Ismail", "Binte Zainal"]
  Indian:
    male_first_names: ["Arjun", "Vikram", "Rahul", "Sanjay"]
    female_first_names: ["Priya", "Anita", "Meena"]
    last_names: ["Singh", "Kumar", "Nair", "Pillai", "Menon", "Rao"]
  Eurasian:
    male_first_names: ["James", "Michael"]
    female_first_names: ["Emma", "Sophia"]
    last_names: ["Pereira", "De Souza", "Fernandez", "Gomes"]
  Filipino:
    male_first_names: ["Jose", "Juan"]
    female_first_names: ["Maria", "Anna", "Clara"]
    last_names: ["Santos", "Reyes", "Cruz", "Garcia"]
  Bangladeshi:
    male_first_names: ["Mohammad", "Abdul", "Rahim"]
    female_first_names: ["Fatima", "Ayesha"]
    last_names: ["Hossain", "Ahmed", "Khan", "Rahman"]
  Caucasian:
    male_first_names: ["James", "Michael", "William", "Harry"]
    female_first_names: ["Emma", "Sophia", "Olivia", "Charlotte"]
    last_names: ["Smith", "Johnson", "Brown", "Taylor", "Wilson"]
  Other:
    male_first_names: ["James", "Michael"]
    female_first_names: ["Emma", "Sophia"]
    last_names: ["Smith", "Brown", "Wilson", "Davis"]

address_components:
  streets:
    [
      "Ang Mo Kio Ave",
      "Bedok North Rd",
      "Bukit Batok St",
      "Choa Chu Kang Loop",
      "Clementi Ave",
      "Hougang Ave",
      "Jurong West St",
      "Pasir Ris Dr",
      "Sengkang East Way",
      "Tampines St",
      "Yishun Ring Rd",
      "Orchard Rd",
      "Geylang Rd",
      "Serangoon Rd",
      "Toa Payoh Lor",
      "Woodlands Dr",
      "Punggol Way",
      "Bishan St",
      "Marine Parade Rd",
      "Eunos Crescent",
      "Queenstown Rd",
      "Balestier Rd",
      "Jalan Besar",
      "Commonwealth Ave",
      "Upper Bukit Timah Rd",
      "Chinatown Point",
      "Tiong Bahru Rd",
      "Kallang Bahru",
      "Boon Lay Way",
      "Admiralty Dr",
    ]

contact_no_prefix: "+65"

email_domains: ["gmail.com", "yahoo.com.sg", "hotmail.com", "outlook.com"]
